# Generated by Django 4.2.29 on 2026-03-23 20:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("circuits", "0022_circuittermination_cloud_network"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0133_alter_approvalworkflowstageresponse_options_and_more"),
        ("dcim", "0081_alter_device_device_redundancy_group_priority_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordinateGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IndividualOptions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("user_id", models.UUIDField(null=True, unique=True)),
                ("ignore_cable_type", models.CharField(blank=True, max_length=255)),
                ("save_coords", models.BooleanField(default=False)),
                ("show_unconnected", models.BooleanField(default=False)),
                ("show_cables", models.BooleanField(default=False)),
                ("show_logical_connections", models.BooleanField(default=False)),
                ("show_single_cable_logical_conns", models.BooleanField(default=False)),
                ("show_neighbors", models.BooleanField(default=False)),
                ("show_circuit", models.BooleanField(default=False)),
                ("show_power", models.BooleanField(default=False)),
                ("draw_default_layout", models.BooleanField(default=False)),
                (
                    "preselected_device_roles",
                    models.ManyToManyField(
                        blank=True,
                        db_table="nautobot_topology_views_individualoptions_preselected_device",
                        related_name="+",
                        to="extras.role",
                    ),
                ),
                (
                    "preselected_tags",
                    models.ManyToManyField(
                        blank=True,
                        db_table="nautobot_topology_views_individualoptions_preselected_tag",
                        related_name="+",
                        to="extras.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoleImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("image", models.CharField(max_length=255)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["content_type", "object_id"], name="nautobot_to_content_971f4f_idx")],
            },
        ),
        migrations.CreateModel(
            name="PowerPanelCoordinate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dcim.powerpanel")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nautobot_topology_views.coordinategroup"
                    ),
                ),
            ],
            options={
                "ordering": ["group", "device"],
                "unique_together": {("device", "group")},
            },
        ),
        migrations.CreateModel(
            name="PowerFeedCoordinate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dcim.powerfeed")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nautobot_topology_views.coordinategroup"
                    ),
                ),
            ],
            options={
                "ordering": ["group", "device"],
                "unique_together": {("device", "group")},
            },
        ),
        migrations.CreateModel(
            name="Coordinate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dcim.device")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nautobot_topology_views.coordinategroup"
                    ),
                ),
            ],
            options={
                "ordering": ["group", "device"],
                "unique_together": {("device", "group")},
            },
        ),
        migrations.CreateModel(
            name="CircuitCoordinate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="circuits.circuit")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nautobot_topology_views.coordinategroup"
                    ),
                ),
            ],
            options={
                "ordering": ["group", "device"],
                "unique_together": {("device", "group")},
            },
        ),
    ]
